/**
 * Typed registry reads, driven by the ARC-56 app specs.
 *
 * Two things this replaces.
 *
 * First, `@algorandfoundation/algokit-utils` was a declared runtime dependency
 * of this package that nothing in `src` imported — the SDK hand-encoded every
 * ABI call against raw algosdk while the Foundation's own client sat unused in
 * the dependency tree.
 *
 * Second, the three ARC-56 specs were generated by the compiler and then
 * abandoned as build output. They carry the method signatures, the struct
 * layouts, and — the part that actually matters here — the `readonly` flag.
 * AppClient routes a readonly method through `simulate`, so the reads below
 * cost nothing and need no signer, where the hand-rolled path either paid a fee
 * or reimplemented box decoding with offset arithmetic that drifts the moment a
 * struct gains a field.
 *
 * The app ids are arguments rather than constants. A previous generation of
 * this SDK hardcoded 768633998 and kept answering reads against a superseded
 * registry long after it was replaced — a dead app does not error, it returns
 * nothing, which is the failure that looks like an answer.
 */

import algosdk from "algosdk";
import { AlgorandClient } from "@algorandfoundation/algokit-utils";
import { AppClient } from "@algorandfoundation/algokit-utils/types/app-client";
import type { Arc56Contract } from "@algorandfoundation/algokit-utils/types/app-arc56";

import identitySpec from "./specs/IdentityRegistry.arc56.json" with { type: "json" };
import reputationSpec from "./specs/ReputationRegistry.arc56.json" with { type: "json" };
import validationSpec from "./specs/ValidationRegistry.arc56.json" with { type: "json" };

/**
 * The AgentInfo tuple, built from the ARC-56 struct definition at module load
 * rather than transcribed. If a field is added to the contract, this follows.
 */
const AGENT_INFO_TUPLE = `(${(
  (identitySpec as unknown as Arc56Contract).structs["AgentInfo"] as {
    name: string;
    type: string;
  }[]
)
  .map((f) => f.type)
  .join(",")})`;

export type RegistryIds = {
  identity: number | bigint;
  reputation: number | bigint;
  validation: number | bigint;
};

export type RegistryNetwork = "mainnet" | "testnet" | "localnet";

/** The registered agent, as the IdentityRegistry's `AgentInfo` struct defines it. */
export type AgentRecord = {
  agentId: bigint;
  domain: string;
  address: string;
  registeredAt: bigint;
  updatedAt: bigint;
};

function algorandFor(network: RegistryNetwork, algodUrl?: string): AlgorandClient {
  if (algodUrl) {
    return AlgorandClient.fromConfig({
      algodConfig: { server: algodUrl, port: "", token: "" },
    });
  }
  if (network === "mainnet") return AlgorandClient.mainNet();
  if (network === "testnet") return AlgorandClient.testNet();
  return AlgorandClient.defaultLocalNet();
}

export class TypedRegistries {
  private readonly algorand: AlgorandClient;
  readonly identity: AppClient;
  readonly reputation: AppClient;
  readonly validation: AppClient;

  constructor(opts: {
    ids: RegistryIds;
    network?: RegistryNetwork;
    algodUrl?: string;
    /** Only needed for calls that write. Every read below is readonly. */
    defaultSender?: string;
  }) {
    const algorand = algorandFor(opts.network ?? "testnet", opts.algodUrl);

    // AppClient needs *an* address to attribute calls to, and the AVM rejects
    // the zero address, so an unfunded throwaway stands in. It never signs.
    //
    // It is only ever enough for the box and global-state reads below. It is
    // NOT enough to simulate an ABI method: simulate still checks the sender
    // could afford the group's minimum fee, so a zero-balance sender fails on
    // overspend. Anything going through `readOnly` therefore takes an explicit
    // funded sender.
    this.algorand = algorand;
    const common = {
      algorand,
      defaultSender: opts.defaultSender ?? algosdk.generateAccount().addr.toString(),
    };

    this.identity = new AppClient({
      ...common,
      appId: BigInt(opts.ids.identity),
      appSpec: identitySpec as unknown as Arc56Contract,
    });
    this.reputation = new AppClient({
      ...common,
      appId: BigInt(opts.ids.reputation),
      appSpec: reputationSpec as unknown as Arc56Contract,
    });
    this.validation = new AppClient({
      ...common,
      appId: BigInt(opts.ids.validation),
      appSpec: validationSpec as unknown as Arc56Contract,
    });
  }

  /**
   * Run a spec-declared readonly method through `simulate` with
   * `skipSignatures`, so it needs neither a signature nor a funded account.
   *
   * `send.call()` would genuinely submit — which for a readonly method means
   * paying a fee to learn something the node will tell you for free, and it
   * fails outright for a caller with no balance. The readonly flag is in the
   * ARC-56 spec; this is what honouring it looks like.
   */
  private async readOnly(
    client: AppClient,
    method: string,
    args: Parameters<AppClient["params"]["call"]>[0]["args"] = [],
    sender?: string
  ): Promise<unknown> {
    const result = await this.algorand
      .newGroup()
      .addAppCallMethodCall(
        await client.params.call({
          method,
          args,
          ...(sender ? { sender } : {}),
        })
      )
      .simulate({ skipSignatures: true });
    return result.returns?.[0]?.returnValue;
  }

  /**
   * Highest agent id ever issued, read from global state.
   *
   * There is also a readonly `total_agents` method, but reaching it means
   * simulating a transaction, and simulate checks the sender could afford the
   * group's minimum fee — so the ABI route needs a funded account to read a
   * public number. Global state needs nothing. Where both exist, this prefers
   * the one that works for a caller with no wallet.
   */
  async totalAgents(): Promise<bigint> {
    const g = await this.identity.getGlobalState();
    return BigInt((g["agent_count"]?.value ?? 0) as bigint);
  }

  /**
   * The ABI route to the same number, for callers that do have a funded
   * address. Kept because it exercises the spec's `readonly` flag end to end,
   * and because it is the only path that proves the deployed program still
   * dispatches that method.
   */
  async totalAgentsViaAbi(sender: string): Promise<bigint> {
    return BigInt((await this.readOnly(this.identity, "total_agents", [], sender)) as bigint);
  }

  /**
   * Resolve a domain to an agent id by reading the `dm_` box directly.
   *
   * The contract keeps this reverse index precisely so a lookup is one box read
   * rather than a scan, and a box read needs no account, no signature and no
   * fee. Routing it through the readonly ABI method instead would need a funded
   * sender — simulate checks the minimum fee is affordable — which would make
   * resolving a public record require a wallet.
   *
   * Zero means "no such record". That is the contract's own answer, not a
   * failure: a missing box and an unreachable node must stay distinguishable,
   * so an absent box returns 0 and only a transport error throws.
   */
  async resolveByDomain(domain: string): Promise<bigint> {
    return this.idFromBox(this.identity, `dm_${domain}`);
  }

  /** Resolve an address to an agent id via the `ad_` box, keyed by public key. */
  async resolveByAddress(address: string): Promise<bigint> {
    const pk = algosdk.decodeAddress(address).publicKey;
    const name = new Uint8Array(3 + pk.length);
    name.set(new TextEncoder().encode("ad_"), 0);
    name.set(pk, 3);
    return this.idFromBox(this.identity, name);
  }

  /** A uint64 box value, or 0 when the box does not exist. */
  private async idFromBox(
    client: AppClient,
    name: string | Uint8Array
  ): Promise<bigint> {
    try {
      const raw = await client.getBoxValue(name);
      if (!raw || raw.length < 8) return 0n;
      return new DataView(raw.buffer, raw.byteOffset, raw.byteLength).getBigUint64(0);
    } catch {
      // algod answers 404 for a box that was never written. That is a record
      // that does not exist, not an error worth propagating.
      return 0n;
    }
  }

  /**
   * Read one agent from its `ag_` box.
   *
   * Decoded with an `ABIType` built from the ARC-56 struct definition, not by
   * slicing at hand-computed offsets. The first version of this method did use
   * offsets and was wrong by two bytes: `agent_domain` is dynamic, so its
   * 2-byte head sits at offset 8 and the address begins at 10, not 8. That is
   * exactly the drift the spec exists to prevent — add a field and every
   * hardcoded offset after it moves.
   */
  async getAgent(agentId: number | bigint): Promise<AgentRecord> {
    const id = BigInt(agentId);
    const name = new Uint8Array(11);
    name.set(new TextEncoder().encode("ag_"), 0);
    new DataView(name.buffer).setBigUint64(3, id);

    const raw = await this.identity.getBoxValue(name);
    const [, domain, address, registeredAt, updatedAt] = algosdk.ABIType.from(
      AGENT_INFO_TUPLE
    ).decode(raw) as [bigint, string, string, bigint, bigint];

    return { agentId: id, domain, address, registeredAt, updatedAt };
  }

  /** The escrow terms the ValidationRegistry was bootstrapped with, from global state. */
  async escrowTerms(): Promise<{
    identityApp: bigint;
    reputationApp: bigint;
    escrowAsset: bigint;
    disputeWindow: bigint;
  }> {
    const g = await this.validation.getGlobalState();
    const u = (k: string) => BigInt((g[k]?.value ?? 0) as bigint);
    return {
      identityApp: u("identity_app"),
      reputationApp: u("reputation_app"),
      escrowAsset: u("escrow_asset"),
      disputeWindow: u("dispute_window"),
    };
  }
}
